version: "3.9"
services:
  example_api:
    build: .
    volumes:
      - ".:/code"
    restart: on-failure
    ports:
      - "9080:9080"
    environment:
      - EXAMPLE_API_CONFIG=/code/sample-config.toml

  webui:
    build:
      context: webui
    restart: on-failure
    volumes:
      - "./webui:/code"
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
    ports:
      - "8080:80"
